spring:
  application:
    name: admin
  config:
    import: classpath:/application-ai.yml
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: rabbitmqroot123
    #虚拟主机
    stream:
      virtual-host: /
    listener:
      simple:
        #消费者的最小数量
        concurrency: 10
        #消费者的最大数量
        max-concurrency: 10
        #限制消费者，每次只能处理一条消息，处理完才能继续下一条消息
        prefetch: 1
        #启动时，是否默认启动容器，默认true
        auto-startup: true
        #被拒绝后，重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        #启用重试机制，默认为false
        enabled: true
        #设置初始化的重试时间间隔
        initial-interval: 1000ms
        #重试最大次数，默认是3
        max-attempts: 3
        #重试最大时间间隔，默认是10s
        max-interval: 10000ms
        #重试时间间隔的乘数
        multiplier: 1
server:
  port: 8080